// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8RoaNWgPkgOnvEeHgqOkLqtltuxSRkGk',
    appId: '1:950900102499:web:5ee6fadbaee65a9cdd2f56',
    messagingSenderId: '950900102499',
    projectId: 'future-builder-8dadb',
    authDomain: 'future-builder-8dadb.firebaseapp.com',
    storageBucket: 'future-builder-8dadb.firebasestorage.app',
    measurementId: 'G-QSHXHTG7EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1tFL3GNRc96ExJUnV86WwX84BJlQbEmM',
    appId: '1:950900102499:android:e6fc56668db39ec8dd2f56',
    messagingSenderId: '950900102499',
    projectId: 'future-builder-8dadb',
    storageBucket: 'future-builder-8dadb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL46JbhZSXt9dyQGfTUR8dO6puYQ2QJTw',
    appId: '1:950900102499:ios:abf0ad30808582d4dd2f56',
    messagingSenderId: '950900102499',
    projectId: 'future-builder-8dadb',
    storageBucket: 'future-builder-8dadb.firebasestorage.app',
    iosBundleId: 'com.example.futureBuilderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL46JbhZSXt9dyQGfTUR8dO6puYQ2QJTw',
    appId: '1:950900102499:ios:abf0ad30808582d4dd2f56',
    messagingSenderId: '950900102499',
    projectId: 'future-builder-8dadb',
    storageBucket: 'future-builder-8dadb.firebasestorage.app',
    iosBundleId: 'com.example.futureBuilderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8RoaNWgPkgOnvEeHgqOkLqtltuxSRkGk',
    appId: '1:950900102499:web:25c706d9fe4a04ebdd2f56',
    messagingSenderId: '950900102499',
    projectId: 'future-builder-8dadb',
    authDomain: 'future-builder-8dadb.firebaseapp.com',
    storageBucket: 'future-builder-8dadb.firebasestorage.app',
    measurementId: 'G-1J8Z5T5W9S',
  );
}
